version: 2.1
jobs:
  build:
    docker:
      - image: node:10.13.0
    working_directory: ~/portfolio-website
    aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID  # can specify string literal values
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY  # or project UI envar referencesxx
    steps:
      - checkout
      - run:
          name: Install Gatsby
          command: npm install -g gatsby
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Generate static website
          command: |
            gatsby build
      - run:
          name: Install AWS CLI
          command: |
            apt-get update
            apt-get install -y awscli
      - run:
          name: Assume Role
          command: |
            chmod +x scripts/aws-cli-assumerole.sh
            source scripts/aws-cli-assumerole.sh