Description: Website S3 Bucket
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvironmentName:
    Type: String
  OriginAccessId:
    Type: String
  CanonicalUser:
    Type: String
Conditions:
  DeployCloudFront: !Not
    - !Equals 
      - !Ref EnvironmentName
      - dev
Resources:
  WebsiteBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub pk-portfolio-website-${EnvironmentName}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: 
              - s3:GetObject
              - s3:PutObject
            Resource: !Sub arn:aws:s3:::${WebsiteBucket}/*
            Condition:
              Bool:
                aws:SecureTransport: false
          - Effect: Allow
            Action: 
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${WebsiteBucket}/*
            Principal:
              CanonicalUser: !Ref CanonicalUser

  websiteCloudfrontdistribution:
    Type: AWS::CloudFront::Distribution
    Condition: DeployCloudFront
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt WebsiteBucket.DomainName
          Id: s3ProductionBucket
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessId}
        Enabled: true
        Comment: TestDistribution
        DefaultRootObject: index.html
        CustomErrorResponses:
        - ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: s3ProductionBucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:123456789012:certificate/364912a52-3115-4df9-a067-7290c0a2657s
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only

